/* Generated by bin2c, do not edit manually */
#ifndef __source_slot1_h_included
#define __source_slot1_h_included

/* Contents of file slot1.bin */
extern const long int slot1_bin_size;
extern const unsigned char slot1_bin[3072];

#endif    /* __source_slot1_h_included */
